# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 150, 401, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.sizex = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.sizex.setObjectName("sizex")
        self.verticalLayout_6.addWidget(self.sizex)
        self.sizey = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.sizey.setObjectName("sizey")
        self.verticalLayout_6.addWidget(self.sizey)
        self.speed = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.speed.setObjectName("speed")
        self.verticalLayout_6.addWidget(self.speed)
        self.count = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.count.setObjectName("count")
        self.verticalLayout_6.addWidget(self.count)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(460, 150, 261, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.line_sizex = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.line_sizex.setObjectName("line_sizex")
        self.verticalLayout_7.addWidget(self.line_sizex)
        self.line_sizey = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.line_sizey.setObjectName("line_sizey")
        self.verticalLayout_7.addWidget(self.line_sizey)
        self.line_speed = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.line_speed.setObjectName("line_speed")
        self.verticalLayout_7.addWidget(self.line_speed)
        self.line_count = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.line_count.setObjectName("line_count")
        self.verticalLayout_7.addWidget(self.line_count)
        self.back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back.setGeometry(QtCore.QRect(330, 370, 75, 24))
        self.back.setObjectName("back")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 814, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sizex.setText(_translate("MainWindow", "Размер поля по горизотали"))
        self.sizey.setText(_translate("MainWindow", "Размер поля по вертикали"))
        self.speed.setText(_translate("MainWindow", "Скорость змейки"))
        self.count.setText(_translate("MainWindow", "Количество фруктов, которые могут находится на поле одновременно"))
        self.back.setText(_translate("MainWindow", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
